repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: uv run ruff check --fix
        language: system
        types: [python]
        pass_filenames: true
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        types: [python]
        pass_filenames: true
# the namespace imports for meta all trigger
#  - repo: local
#    hooks:
#      - id: system
#        name: flake8
#        entry: poetry run flake8 src/
#        language: system
#        pass_filenames: false